### DISCUSSION TITLE
Using rating.gte on Plex Genre Collections

### DISCUSSION THREAD

**Discussion by b101marc** [meisnate12/Plex-Meta-Manager-Configs#17] [Q&A]
Wanted to pull genre collections but only over or meeting a certain rating however my config must be off. I'm going off of the collection filters examples. 

Here are a couple of examples from my Movies.yml
```
Sci-Fi:
    plex_search:
      genre: Science Fiction
      filters:
        rating.gte: 7
```

Results in: 
```
| Scanning Sci-Fi Collection                                                                         |
| Collection Error: filters plex search attribute not supported  
```

Additionally trying to do the same for a Romantic Comedies collection:

```
Romantic Comedy:
    plex_search:
      genre: Romance
    filters:
        genre: Comedy
        rating.gte: 7
    sort_title: ++_Romantic Comedy
```
Results in:
```
| Scanning Romantic Comedy Collection                                                                |
|                                                                                                    |
| Sync Mode: append                                                                                  |
|                                                                                                    |
| Collection Filter genre: ['Comedy']                                                                |
| Collection Filter rating.gte: 7.0                                                                  |
|                                                                                                    |
| Processing Plex Search: genre(Romance)                                                             |
| Unknown Error: '<' not supported between instances of 'NoneType' and 'float' 
```

Insight appreciated as always!

**Comment by meisnate12** [comment]
for this one:
```yaml
Sci-Fi:
    plex_search:
      genre: Science Fiction
      filters:                # <------ This shouldn't be under plex_search
        rating.gte: 7
```
do this 
```yaml
Sci-Fi:
    plex_search:
      genre: Science Fiction
    filters:
      rating.gte: 7
```
however this
```
Unknown Error: '<' not supported between instances of 'NoneType' and 'float' 
```
is an actual bug can you look at this line in your meta.log file and send me the trace back above it
