### DISCUSSION TITLE
Collection Visible Shared and Home cannot be turned off once on.

### DISCUSSION THREAD

**Discussion by DutchyOven** [meisnate12/Plex-Meta-Manager-Configs#34] [Q&A]
I had an idea that I could have two versions of all my seasonal collections, that become visible on home page only on certain times of the year.

For instance below I have two templates for holidays and two collections, same name and attributes, except the sort name changes and visibility on home page changes.

Turning a collection that's not visible, to visible works fine. Turning it off from visible does not seem to work. Is there something I should be doing? 

Example below....

on 7/6 Coming of Age becomes visible, sorting name pushes it to the top

on 8/31 Coming of Age changes to not visible, sorting name pushes it to the bottom.

All works except for the visible part on 8/31

```
templates:
    Holiday:
        url_poster: <<poster>>
        sort_title: "'''_<<collection_name>>"
        smart_label: random
        visible_home: true
        visible_shared: true
        radarr_monitor: true
        radarr_add: true
        radarr_search: true
        # collection_order: release
    Holiday_Off:
        url_poster: <<poster>>
        sort_title: "z_<<collection_name>>"
        smart_label: release.desc
        visible_home: false
        visible_shared: false
        radarr_monitor: true
        radarr_add: true
        radarr_search: true
        # collection_order: release
collections:
  Coming of Age:
    template: {name: Holiday, poster: https://imgpile.com/images/N6r0Oa.jpg}
    trakt_list:
      - https://trakt.tv/users/galacticboy/lists/coming-of-age
    summary: A mix of coming of age movies.
    schedule: yearly(07/06)
  Coming of Age:
    template: {name: Holiday_Off, poster: https://imgpile.com/images/N6r0Oa.jpg}
    trakt_list:
      - https://trakt.tv/users/galacticboy/lists/coming-of-age
    summary: A mix of coming of age movies.
    schedule: yearly(08/31)
    radarr_tag: metacomingofage
```

**Comment by DutchyOven** [comment]
I put this in the wrong section, not -configs section.

**Comment by meisnate12** [comment]
So I'm not sure about the visibility issue I'll look into that. But I also notice that both those collection keys are the same name which means isn't not a valid yaml file does that load correctly.

Also very creative use of scheduling

**Reply by DutchyOven** [reply]
Hey I double asked this question, thought I put it in the wrong place blah blah if you can erase the new one that'd be great. Can't figure out how to delete, don't comment much on github.

I've never tried it with both uncommented, was just trying each one at a time and you are correct! back to the drawing board then, ha! 

I'll probably end up making two movie.yml's or something who knows!

**Reply by meisnate12** [reply]
i deleted the regular one without realizing exact what you did haha. It's fine here. I could add a `collection_name` Collection Detail which when used is what the collection will be named so you could then do.

```yaml
templates:
    Holiday:
        url_poster: <<poster>>
        sort_title: "'''_<<collection_name>>"
        smart_label: random
        visible_home: true
        visible_shared: true
        radarr_monitor: true
        radarr_add: true
        radarr_search: true
        # collection_order: release
    Holiday_Off:
        url_poster: <<poster>>
        sort_title: "z_<<collection_name>>"
        smart_label: release.desc
        visible_home: false
        visible_shared: false
        radarr_monitor: true
        radarr_add: true
        radarr_search: true
        # collection_order: release
collections:
  Coming of Age Holiday On:
    template: {name: Holiday, poster: https://imgpile.com/images/N6r0Oa.jpg}
    trakt_list:
      - https://trakt.tv/users/galacticboy/lists/coming-of-age 
    collection_name: Coming of Age
    summary: A mix of coming of age movies.
    schedule: yearly(07/06)
  Coming of Age Holiday Off:
    template: {name: Holiday_Off, poster: https://imgpile.com/images/N6r0Oa.jpg}
    trakt_list:
      - https://trakt.tv/users/galacticboy/lists/coming-of-age
    collection_name: Coming of Age
    summary: A mix of coming of age movies.
    schedule: yearly(08/31)
    radarr_tag: metacomingofage
```

**Reply by DutchyOven** [reply]
That'd work, maybe have a script that runs in between and erases the collection and rebuilds it on the day it turns to off that way I don't have two collections floating around.

**Reply by meisnate12** [reply]
I don't have anything in PMM that will delete collections but it would be an easy script to write I might even add it in as well like if the collection is below a threshold number of items delete it/don't create it

**Reply by DutchyOven** [reply]
I could technically, maybe? Use PlexAPI https://python-plexapi.readthedocs.io/en/latest/modules/collection.html

I run a lot of PlexAPI scripts for stuff, actually used it for my collections until PMM.

There is a delete function there I just need to figure out how to use it to delete smart collections, HA! 

My frankenstein method is make a script to delete  _Coming of Age Holiday On_ , use crontab to run it at on 8/30 at 11pm, using PlexAPI, then PMM runs _Coming of Age Holiday Off_ on 8/31.

Or I just set a calendar alert on my phone, walk over to my server, press visible like a sane person LOL

Thanks though

**Reply by DutchyOven** [reply]
So I figured out how to do it. Make my normal seasonal collections that sit there year round and update themselves weekly. Then have PMM make a visible version of a seasonal collection one time of year and have plexapi delete it.

Nov 30th - PMM makes "Its the most wonderful time of the year collection"
Dec 26th - PlexAPI deletes "Its the most wonderful time of the year collection"
All Year - Christmas Collection updates weekly and is not visible on home page

Example 
Movies.yml

```yaml
###########################
#        Templates        #
###########################
templates:
    Holiday:
        url_poster: <<poster>>
        sort_title: "z_<<collection_name>>"
        smart_label: random
        visible_home: true
        visible_shared: true
    Holiday_Off:
        file_poster: <<poster>>
        sort_title: "#_<<collection_name>>"
        smart_label: release.desc
        visible_home: false
        visible_shared: false

collections:
###########################
# Holiday Collections ON  #
###########################
  Its the Most Wonderful Time of the Year:
    template: {name: Holiday, poster: /config/posters/paintings/christmas.jpg}
    trakt_list:
      - https://trakt.tv/users/movistapp/lists/christmas-movies
      - https://trakt.tv/users/galacticboy/lists/xmas-sync
    imdb_list:
      - https://www.imdb.com/list/ls025976544/
      - https://www.imdb.com/list/ls003863000/
      - https://www.imdb.com/list/ls027454200/
      - https://www.imdb.com/list/ls097998599/
    summary: Christmas film is a genre that revolves around the plot involving Christmas. 
    schedule: yearly(11/30) #11/30 - 12/26
###########################
#   Holiday Collections   #
###########################
  Christmas:
    template: {name: Holiday_Off, poster: /config/posters/paintings/christmas.jpg}
    trakt_list:
      - https://trakt.tv/users/movistapp/lists/christmas-movies
      - https://trakt.tv/users/galacticboy/lists/xmas-sync
    imdb_list:
      - https://www.imdb.com/list/ls025976544/
      - https://www.imdb.com/list/ls003863000/
      - https://www.imdb.com/list/ls027454200/
      - https://www.imdb.com/list/ls097998599/
    summary: Christmas film is a genre that revolves around the plot involving Christmas.
    schedule: weekly(sunday)

```



Run remove_christmas.py on December 26th using crontab

0 1 26 12 *  /usr/bin/python3 /mnt/ssd/docker/tautulli/plexapi_scripts/remove_christmas.py

```python
from plexapi.server import PlexServer
baseurl = 'http://192.168.1.1:32400'
token = '546faketoken1beh'
plex = PlexServer(baseurl, token)

moviesLibrary = plex.library.section("Movies")
collection = moviesLibrary.collection("Its the Most Wonderful Time of the Year")
collection.delete()
```
