### DISCUSSION TITLE
Creating a Collection with both Trakt and IMDb

### DISCUSSION THREAD

**Discussion by b101marc** [meisnate12/Plex-Meta-Manager-Configs#4] [Q&A]
Hi all,

Having some trouble with my metadata file. I'm wanting to append an existing collection I had made using Plex-Auto-Collections with both a trakt and imdb list. Currently that section in my metadata file looks like this:

```
Queer:
    trakt_list:
    - https://trakt.tv/users/outtherek/lists/queer/
    - https://trakt.tv/users/igiorgis/lists/lgbt-lesbian-gay-bisexual-transgender-movies-tv-shows-the-biggest-list-on-trakt/
    imdb_list:
    - url: https://www.imdb.com/list/ls062688328/?sort=date_added,desc&st_dt=&mode=detail&page=1
    synd mode: append
```

Currently it seems to only be pulling from the first list under trakt. Any guidance much appreciated.

Edit: Didn't realize I was in the Configs repo and not the main. My bad.

**Comment by meisnate12** [comment]
can you post your log file?

**Reply by b101marc** [reply]
[meta.txt](https://github.com/meisnate12/Plex-Meta-Manager-Configs/files/5959662/meta.txt)

**Reply by meisnate12** [reply]
can you upload your metadata file as well you YAML might be formatted incorrectly because when I make that collection in my environment all the lists work as intended. Also `sync mode` should have an underscore so it would be `sync_mode`

**Reply by b101marc** [reply]
Here is the YAML. Won't let me upload here so here is a drive link.

[YAML](https://drive.google.com/file/d/1DMtNlNBObe0FkI7VjtFgDOdoSoa2BLtN/view?usp=sharing
)

**Reply by meisnate12** [reply]
can you switch to the develop branch and run it again and then send me the log file

**Reply by meisnate12** [reply]
if your using docker the develop version of that was just updated

**Reply by b101marc** [reply]
I'm not using docker, would it be best to switch over to that instead of local install?

**Reply by meisnate12** [reply]
its really whatever works best with your setup there also the develop branch on the git that is the same as the docker instance.

**Reply by b101marc** [reply]
Sort of a silly question, but is there a specific way for me to pull the develop brand for local install? I already have this installed and running so didn't want to fuss with docker.

**Reply by meisnate12** [reply]
do you use git or do you just download the files from the site?

on github the develop branch is here https://github.com/meisnate12/Plex-Meta-Manager/tree/develop

if you use git just check out the develop branch `git checkout develop` i think

**Reply by b101marc** [reply]
I'm just running `git clone https://github.com/meisnate12/Plex-Meta-Manager.git`

**Reply by meisnate12** [reply]
ok run `git checkout develop`

**Reply by b101marc** [reply]
Will do, will this overwrite the existing files?

**Reply by meisnate12** [reply]
yes but you should be able to use `git checkout master` to go back.

It shouldn't mess with any new files you've created ie config.yml and Movies.yml but you could always make a copy of the whole folder just in case

**Reply by b101marc** [reply]
Gotcha. Will do.

I made that adjustment and am running now, and from your own template I just tried running one of the examples the includes both a trakt and imdb list and it's only pulling the one list. This is what is inside the metadata file:

  ```
Christmas:
    trakt_list:
      - https://trakt.tv/users/movistapp/lists/christmas-movies
      - https://trakt.tv/users/2borno2b/lists/christmas-movies-extravanganza
    imdb_list:
      - https://www.imdb.com/list/ls025976544/
      - https://www.imdb.com/list/ls003863000/
      - https://www.imdb.com/list/ls027454200/
      - https://www.imdb.com/list/ls027886673/
      - https://www.imdb.com/list/ls097998599/
    sort_title: ++_Christmas
    sync_mode: append
    summary: Christmas film is a genre that revolves around the plot involving Christmas.
    collection_order: alpha
```
