### DISCUSSION TITLE
Using Plex builders to create multi-genre collections

### DISCUSSION THREAD

**Discussion by b101marc** [meisnate12/Plex-Meta-Manager-Configs#6] [Q&A] [answered]
Is it possible to use the plex builders to build Collections like Romantic Comedies using genre filters? Maybe something like:

```
collections:
  Romantic Comedies:
    plex_search:
      genre: Comedy
        genre: Romance
```

Reason: I want it to be able to create a collection regardless of date or rating.

**Comment by meisnate12** [comment, marked as answer]
Use a [collection filter](https://github.com/meisnate12/Plex-Meta-Manager/wiki/Collection-Filters) like so:

```yaml
collections:
  Romantic Comedies:
    genre: Romance
    filters:
      genre: Comedy
```
