### ISSUE TITLE
[Bug]: Incorrect overlay for AC3 Stereo

### ISSUE THREAD

**Issue by rcdailey** [meisnate12/Plex-Meta-Manager-Configs#306]
### Link to File

https://github.com/meisnate12/Plex-Meta-Manager-Configs/blob/master/PMM/overlays/audio_codec.yml

### Version Number

1.17

### What branch are you on?

master

### Describe the Bug

![image](https://user-images.githubusercontent.com/1768054/170616676-499ef0b8-c3b1-47b9-a466-2bb889ecd6fd.png)

In this screenshot, you'll see that this movie is AC3 Stereo, but the overlay that gets attached is "Dolby Digital". Maybe I'm misinformed, but when I see "Dolby" on anything I don't immediately think of 2.0 stereo.

My feeling is that this should have a different overlay without "Dolby" in the name. If I'm wrong, please educate me on why this is the correct overlay.

My PMM YAML:

```yml
libraries:
  Movies:
    overlay_path:
    - git: PMM/overlays/resolution
    - git: PMM/overlays/audio_codec
    operations:
      delete_unmanaged_collections: true
      mass_content_rating_update: mdb
```
