### ISSUE TITLE
[Bug]: rt_cert_fresh doesn't work for shows

### ISSUE THREAD

**Issue by karan** [meisnate12/Plex-Meta-Manager-Configs#394]
### Link to File

https://github.com/meisnate12/Plex-Meta-Manager-Configs/blob/master/PMM/overlays/rt_cert_fresh.yml

### Version Number

1.17.2

### What branch are you on?

master

### Describe the Bug

`rt_cert_fresh` should work for shows as well with this setting:

```
  TV Shows:
    operations:
      mass_audience_rating_update: imdb
      mass_critic_rating_update: mdb_tomatoes
      mass_episode_critic_rating_update: imdb
      mass_episode_audience_rating_update: tmdb
    metadata_path:
      - file: config/plex-meta-manager-shows.yml
    overlay_path:
      - remove_overlays: false
      - git: PMM/overlays/rt_cert_fresh
      - git: PMM/overlays/rt_cert_fresh
        template_variables:
          overlay_level: episode
      - git: PMM/overlays/rt_cert_fresh
        template_variables:
          overlay_level: season
```

But, the log shows no overlays were generated:

```
[2022-07-23 22:26:47,835] [plex_meta_manager.py:349]  [INFO]     |========================================= TV Shows Summary =========================================|
[2022-07-23 22:26:47,835] [plex_meta_manager.py:350]  [INFO]     |                                                                                                    |
[2022-07-23 22:26:47,835] [plex_meta_manager.py:351]  [INFO]     | Title                       | Run Time |                                                           |
[2022-07-23 22:26:47,835] [plex_meta_manager.py:352]  [INFO]     | =========================== | ======== |                                                           |
[2022-07-23 22:26:47,836] [plex_meta_manager.py:355]  [INFO]     | Library Loading and Mapping |  0:00:01 |                                                           |
[2022-07-23 22:26:47,836] [plex_meta_manager.py:355]  [INFO]     | Library Metadata Files      |  0:02:57 |                                                           |
[2022-07-23 22:26:47,836] [plex_meta_manager.py:355]  [INFO]     | Library Operations          |  0:01:21 |                                                           |
[2022-07-23 22:26:47,836] [plex_meta_manager.py:355]  [INFO]     | Library Overlays            |  0:00:00 |                                                           |```

```
[2022-07-23 22:26:44,240] [builder.py:196]            [INFO]     |====================================================================================================|
[2022-07-23 22:26:44,240] [builder.py:196]            [INFO]     |                              RT-Cert-Fresh-Ribbon Overlay in TV Shows                              |
[2022-07-23 22:26:44,240] [builder.py:196]            [INFO]     |====================================================================================================|
[2022-07-23 22:26:44,240] [builder.py:197]            [INFO]     |                                                                                                    |
[2022-07-23 22:26:44,240] [builder.py:202]            [INFO]     |============================ Validating RT-Cert-Fresh-Ribbon Attributes ============================|
[2022-07-23 22:26:44,240] [builder.py:223]            [DEBUG]    |                                                                                                    |
[2022-07-23 22:26:44,240] [builder.py:224]            [DEBUG]    | Validating Method: template                                                                        |
[2022-07-23 22:26:44,241] [meta.py:112]               [DEBUG]    | Value: [ordereddict([('name', 'RTCertFresh')])]                                                    |
[2022-07-23 22:26:44,241] [util.py:939]               [DEBUG]    |                                                                                                    |
[2022-07-23 22:26:44,241] [util.py:940]               [DEBUG]    | Validating Method: overlay                                                                         |
[2022-07-23 22:26:44,241] [util.py:941]               [DEBUG]    | Value: {'name': 'RT-Cert-Fresh-Ribbon', 'git': 'PMM/overlays/images/RT-Cert-Fresh-Ribbon', 'group': 'ribbon', 'weight': 20, 'horizontal_offset': 0, 'horizontal_align': 'right', 'vertical_offset': 0, 'vertical_align': 'bottom'} |
[2022-07-23 22:26:44,431] [builder.py:613]            [DEBUG]    |                                                                                                    |
[2022-07-23 22:26:44,431] [builder.py:617]            [DEBUG]    | Validating Method: mdblist_list                                                                    |
[2022-07-23 22:26:44,431] [builder.py:618]            [DEBUG]    | Value: https://mdblist.com/lists/plexmetamanager/certifiedfreshmovies                              |
[2022-07-23 22:26:44,432] [builder.py:780]            [INFO]     |                                                                                                    |
[2022-07-23 22:26:44,432] [builder.py:781]            [INFO]     | Validation Successful                                                                              |
[2022-07-23 22:26:44,432] [overlays.py:303]           [INFO]     |                                                                                                    |
```

This seems like it's happening because it's using `https://mdblist.com/lists/plexmetamanager/certifiedfreshmovies` to query items which only contains movies and not shows/seasons/episodes.
