### ISSUE TITLE
Config Error: tmdb attribute not found 

### ISSUE THREAD

**Issue by squk** [meisnate12/Plex-Meta-Manager-Configs#5]
Using the following config: 
```yml
collections:
  Spider-Man:
    imdb_list: https://www.imdb.com/list/ls049852613/
    summary: A collection of all Spider-Man movies.
    sort_title: '+005'
```

```
| Config Error: tmdb attribute not found                                                             |
```
