### ISSUE TITLE
[Bug]: Edition bug in PMM overlay config.

### ISSUE THREAD

**Issue by shifatul-i** [meisnate12/Plex-Meta-Manager-Configs#539]
### Link to File

https://github.com/meisnate12/Plex-Meta-Manager-Configs/blob/master/PMM/overlays/resolution.yml

### Version Number

Latest

### What branch are you on?

master

### Describe the Bug

Edition used to look like this:
![image](https://user-images.githubusercontent.com/3328263/212562864-d52a9c94-354d-4746-a80a-ef14ada85c86.png)

Now it looks like this:
![image](https://user-images.githubusercontent.com/3328263/212562848-c0125710-d7d9-4425-b2a0-a1e94b59de9d.png)

```
- git: PMM/overlays/resolution
  template_variables:
    horizontal_offset: 15
    horizontal_align: left
    vertical_offset: 15
    vertical_align: top
    use_4k: true
    use_1080p: false
    use_720p: false
    use_576p: false
    use_480p: false
    use_dv: true
    use_hdr: true
```
